title: Designing Data Strategies for Complex Customer Relationships
description: Learning Lab Repository Related to the B2B Solution Architect Program
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
